name: Build Qt5 i686 Windows App (Static Qt MSVC x86)

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        shell: powershell
        run: |
          choco install strawberryperl python3 -y
          git config --global core.autocrlf false

      - name: Download Qt 5.15.2 Source
        run: |
          curl -LO https://download.qt.io/official_releases/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.zip
          tar -xf qt-everywhere-src-5.15.2.zip
          ren qt-everywhere-src-5.15.2 QtSrc

      - name: Configure Qt for Static MSVC x86
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cd QtSrc
          configure -static -release -platform win32-msvc ^
            -prefix C:\QtInstall ^
            -opensource -confirm-license ^
            -nomake examples -nomake tests ^
            -skip qtwebengine

      - name: Build and Install Static Qt
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cd QtSrc
          nmake
          nmake install

      - name: Build EmpireEarthZoomChanger
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          set PATH=C:\QtInstall\bin;%PATH%
          qmake CONFIG+=release EmpireEarthZoomChanger.pro
          nmake

      - name: Set tag name (YYYY-MM-DD)
        id: set_date_tag
        shell: bash
        run: |
          echo "now=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: release/EmpireEarthZoomChanger.exe
          name: Compiled CI/CD artifact
          body: "Latest i686 (x32) Qt5 app built automatically by GitHub Actions"
          tag_name: "release-${{ steps.set_date_tag.outputs.now }}"
