name: Build Qt5 i686 Windows App with MSYS2

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-i686-toolchain
            mingw-w64-i686-qt5
            mingw-w64-i686-cmake
            mingw-w64-i686-make
            git

      - name: Add MinGW to PATH
        run: echo "C:/msys64/mingw32/bin" >> $GITHUB_PATH

      - name: Build with qmake
        run: |
          cd ${{ github.workspace }}
          qmake
          make -j$(nproc)

      - name: Archive the build
        uses: actions/upload-artifact@v4
        with:
          name: EmpireEarthZoomChanger
          path: EmpireEarthZoomChanger.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: EmpireEarthZoomChanger

      - name: Generate date-based tag name
      - name: Prepare date-based tag name
        run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          name: Compiled CI/CD artifact
          body: "Latest i686 (x32) Qt5 app built automatically by GitHub Actions (MSYS2)"
          tag_name: "release-${{ env.NOW }}"
          files: release/EmpireEarthZoomChanger.exe